@extends('layouts.app')

@section('content')
<div class="row mb-4">
    <div class="col-md-8">
        <h2 class="animate__animated animate__fadeInLeft">Legacy Telemetry Data</h2>
        <p class="text-muted">Data generated by the Pascal Legacy System</p>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                <span>Telemetry History</span>
                <span class="badge bg-accent text-dark">Total: {{ count($telemetry) }}</span>
            </div>
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Recorded At</th>
                            <th>Status</th>
                            <th>Value</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($telemetry as $row)
                        <tr class="animate__animated animate__fadeInUp">
                            <td>{{ $row->recorded_at }}</td>
                            <td>
                                @if($row->is_active)
                                    <span class="badge bg-success">ACTIVE</span>
                                @else
                                    <span class="badge bg-danger">INACTIVE</span>
                                @endif
                            </td>
                            <td>{{ $row->value }}</td>
                            <td class="small text-muted">{{ $row->description }}</td>
                        </tr>
                        @empty
                        <tr><td colspan="4" class="text-center py-5 text-muted">No telemetry records found</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

